## 一、上市公司财务数据采集代码

根据文档，TRACE 项目需要六大数据类。以下是整理的真实有效的数据类型和渠道列表：

  ---
  一、上市公司财务数据

  ┌──────────┬─────────────────────────────────────────┬────────────────────────────────────┬─────┬─────────────────────────┐
  │ 数据类型 │                具体内容                 │        采集渠道（真实有效）        │ 频  │          说明           │
  │          │                                         │                                    │ 率  │                         │
  ├──────────┼─────────────────────────────────────────┼────────────────────────────────────┼─────┼─────────────────────────┤
  │          │                                         │ AKShare (ak.stock_financial_balanc │     │ Tushare                 │
  │ 资产负债 │ 总资产、负债、流动资产、非流动资产、所  │ e_sheet_em) 、Tushare Pro          │ 季  │ 积分门槛较高，AKShare   │
  │ 表       │ 有者权益等                              │ (balancesheet，需积分≥2000)        │ 度  │ 通过东方财富接口免费获  │
  │          │                                         │                                    │     │ 取，更推荐              │
  ├──────────┼─────────────────────────────────────────┼────────────────────────────────────┼─────┼─────────────────────────┤
  │          │ 营业收入、营业成本、净利润、管理费用、  │ AKShare (ak.stock_financial_profit │ 季  │                         │
  │ 利润表   │ 财务费用等                              │ _income_statement_em) 、Tushare    │ 度  │ 同上，AKShare 零门槛    │
  │          │                                         │ Pro (income)                       │     │                         │
  ├──────────┼─────────────────────────────────────────┼────────────────────────────────────┼─────┼─────────────────────────┤
  │ 现金流量 │ 经营活动现金流、投资活动现金流、筹资活  │ AKShare (ak.stock_financial_cash_f │ 季  │                         │
  │ 表       │ 动现金流                                │ low_statement_em) 、Tushare Pro    │ 度  │ —                       │
  │          │                                         │ (cashflow)                         │     │                         │
  ├──────────┼─────────────────────────────────────────┼────────────────────────────────────┼─────┼─────────────────────────┤
  │ 公司基本 │ 股票代码、公司全称、行业分类（申万）、  │ AKShare                            │ 日  │                         │
  │ 信息     │ 上市日期、ST状态                        │ (ak.stock_info_a_code_name)        │ 更  │ 用于标签构建和行业分类  │
  │          │                                         │ 、Tushare Pro (stock_basic)        │     │                         │
  └──────────┴─────────────────────────────────────────┴────────────────────────────────────┴─────┴─────────────────────────┘

  二、市场行情数据

  ┌────────────┬────────────────────────────────────────┬──────────────────────┬───────────────┬────────────────────────────┐
  │  数据类型  │                具体内容                │       采集渠道       │     频率      │            说明            │
  ├────────────┼────────────────────────────────────────┼──────────────────────┼───────────────┼────────────────────────────┤
  │            │                                        │ AKShare              │               │                            │
  │ 日线OHLCV  │ 开盘价、最高价、最低价、收盘价、成交量 │ (ak.stock_zh_a_hist) │ 日线，需按季  │ 构建季度收益率、波动率、最 │
  │            │ 、成交额（前复权）                     │  、Tushare Pro       │ 度聚合        │ 大回撤、Beta               │
  │            │                                        │ (daily，需积分)      │               │                            │
  ├────────────┼────────────────────────────────────────┼──────────────────────┼───────────────┼────────────────────────────┤
  │ 沪深300指  │                                        │ AKShare (ak.stock_zh │               │                            │
  │ 数日线     │ 基准指数行情                           │ _index_daily，代码   │ 日线          │ 用于计算个股 Beta          │
  │            │                                        │ sh000300)            │               │                            │
  ├────────────┼────────────────────────────────────────┼──────────────────────┼───────────────┼────────────────────────────┤
  │ 中债国债收 │ 1年期、10年期国债收益率                │ AKShare (ak.bond_chi │ 日线，按季度  │ 无风险利率锚               │
  │ 益率       │                                        │ na_yield)            │ 均值聚合      │                            │
  └────────────┴────────────────────────────────────────┴──────────────────────┴───────────────┴────────────────────────────┘

  三、宏观经济指标

  ┌──────────┬────────────────────────────────────────┬─────────────────────────────────────┬───────────────┬──────────────────┐
  │ 数据类型 │                具体指标                │              采集渠道               │     频率      │       说明       │
  ├──────────┼────────────────────────────────────────┼─────────────────────────────────────┼───────────────┼──────────────────┤
  │ GDP增速  │ 中国GDP当季同比                        │ AKShare (ak.macro_china_gdp)        │ 季度          │ —                │
  │          │                                        │ 、国家统计局官网                    │               │                  │
  ├──────────┼────────────────────────────────────────┼─────────────────────────────────────┼───────────────┼──────────────────┤
  │          │                                        │ AKShare                             │               │                  │
  │ CPI      │ 居民消费价格指数同比                   │ (ak.macro_china_cpi_monthly)        │ 月度→季度均值 │ —                │
  │          │                                        │ 、东方财富                          │               │                  │
  ├──────────┼────────────────────────────────────────┼─────────────────────────────────────┼───────────────┼──────────────────┤
  │ PMI      │ 制造业采购经理指数                     │ AKShare (ak.macro_china_pmi)        │ 月度→季度均值 │ 经济景气先行指标 │
  │          │                                        │ 、国家统计局                        │               │                  │
  ├──────────┼────────────────────────────────────────┼─────────────────────────────────────┼───────────────┼──────────────────┤
  │          │                                        │ AKShare                             │               │                  │
  │ M2增速   │ 广义货币供应量同比                     │ (ak.macro_china_money_supply)       │ 月度→季度均值 │ —                │
  │          │                                        │ 、央行官网                          │               │                  │
  ├──────────┼────────────────────────────────────────┼─────────────────────────────────────┼───────────────┼──────────────────┤
  │ 社融规模 │ 社会融资规模增量                       │ AKShare (ak.macro_china_shrzgm)     │ 月度→季度均值 │ 实体经济融资需求 │
  │          │                                        │ 、央行官网                          │               │                  │
  ├──────────┼────────────────────────────────────────┼─────────────────────────────────────┼───────────────┼──────────────────┤
  │ Shibor   │ 上海银行间同业拆放利率（隔夜/1月/1年） │ AKShare (ak.rate_interbank)         │ 日线→季度均值 │ 短期资金面       │
  └──────────┴────────────────────────────────────────┴─────────────────────────────────────┴───────────────┴──────────────────┘

  四、新闻舆情文本数据

  ┌─────────────────┬───────────────────────────────────────┬────────────────────────────────┬────────┬─────────────────────┐
  │    数据类型     │               具体内容                │            采集渠道            │  频率  │        说明         │
  ├─────────────────┼───────────────────────────────────────┼────────────────────────────────┼────────┼─────────────────────┤
  │                 │                                       │ Tushare Pro (news) 、AKShare   │ 持续采 │ 用于情感分类和舆情  │
  │ 财经新闻        │ 新闻标题、摘要、发布时间、来源媒体    │ (ak.stock_news_em，东方财富财  │ 集     │ 冲击指数            │
  │                 │                                       │ 经快讯)                        │        │                     │
  ├─────────────────┼───────────────────────────────────────┼────────────────────────────────┼────────┼─────────────────────┤
  │                 │ 公告标题、摘要、类型（风险警示/业绩预 │ 巨潮资讯网（爬虫）             │ 持续采 │ 负面事件标记关键来  │
  │ 上市公司公告    │ 告/重大合同）                         │ 、东方财富公告                 │ 集     │ 源                  │
  │                 │                                       │ (ak.stock_notice_report_em)    │        │                     │
  ├─────────────────┼───────────────────────────────────────┼────────────────────────────────┼────────┼─────────────────────┤
  │ 券商研报        │ 研报标题、评级、摘要                  │ 东方财富研报                   │ 持续采 │ 用于情绪聚合参考    │
  │                 │                                       │ (ak.stock_research_report_em)  │ 集     │                     │
  ├─────────────────┼───────────────────────────────────────┼────────────────────────────────┼────────┼─────────────────────┤
  │                 │                                       │ THUCNews 金融子集（清华大学NLP │        │                     │
  │ 中文金融NLP预训 │ 金融情感词典                          │ 实验室开源自带分类）           │ 一次性 │ 辅助模型微调和验证  │
  │ 练词库          │                                       │ 、ChnSentiCorp（中文情感分析公 │        │                     │
  │                 │                                       │ 开数据集）                     │        │                     │
  └─────────────────┴───────────────────────────────────────┴────────────────────────────────┴────────┴─────────────────────┘

  五、供应链关系数据

  ┌──────────────┬────────────────────┬───────────────────────────────────┬──────────┬───────────────────────────────────────┐
  │   数据类型   │      具体内容      │             采集渠道              │   频率   │                 说明                  │
  ├──────────────┼────────────────────┼───────────────────────────────────┼──────────┼───────────────────────────────────────┤
  │ 前五大客户/  │ 名称、金额占比、关 │ 上市公司年报/半年报（PDF解析爬虫  │ 年度/半  │ A股披露要求，手工构建CSV，建议≥300对  │
  │ 供应商       │ 联关系             │ 或人工整理） 、东方财富公司概况   │ 年度     │                                       │
  ├──────────────┼────────────────────┼───────────────────────────────────┼──────────┼───────────────────────────────────────┤
  │ 行业共现关系 │ 同行业、同地域企业 │ 申万行业分类（AKShare获取）+      │ 年度更新 │ 图神经网络的补充边（无直接供应链关系  │
  │              │ 聚类               │ 注册地址                          │          │ 时的替代方案）                        │
  ├──────────────┼────────────────────┼───────────────────────────────────┼──────────┼───────────────────────────────────────┤
  │ 股权关联     │ 持股比例、控制关系 │ AKShare (ak.stock_share_holder)   │ 季度     │ 知识图谱股权边构建                    │
  └──────────────┴────────────────────┴───────────────────────────────────┴──────────┴───────────────────────────────────────┘

  六、国际贸易特色数据

  ┌────────────┬──────────────────────────────────────────┬─────────────────────────┬──────────┬─────────────────────────────┐
  │  数据类型  │                 具体内容                 │        采集渠道         │   频率   │            说明             │
  ├────────────┼──────────────────────────────────────────┼─────────────────────────┼──────────┼─────────────────────────────┤
  │            │                                          │ AKShare (ak.index_inves │          │                             │
  │ BDI指数    │ 波罗的海干散货运价指数                   │ ting_global，搜索 BDIY  │ 日线→季  │ 衡量全球大宗商品航运成本，  │
  │            │                                          │ ，Investing.com接口)    │ 度均值   │ 影响外贸企业利润            │
  │            │                                          │ 、Wind（付费）          │          │                             │
  ├────────────┼──────────────────────────────────────────┼─────────────────────────┼──────────┼─────────────────────────────┤
  │ 美元/人民  │                                          │ AKShare                 │          │ 计算汇率敏感系数（滚动回归  │
  │ 币汇率     │ CNY/USD 日收盘价                         │ (ak.currency_boc_sina)  │ 日线     │ ）                          │
  │            │                                          │ 、中国外汇交易中心      │          │                             │
  ├────────────┼──────────────────────────────────────────┼─────────────────────────┼──────────┼─────────────────────────────┤
  │ 中国进出口 │                                          │ 海关总署官网、AKShare   │ 月度→季  │                             │
  │ 金额       │ 月度进出口总额、按HS编码分品类           │ (ak.macro_china_trade_b │ 度       │ —                           │
  │            │                                          │ alance)                 │          │                             │
  ├────────────┼──────────────────────────────────────────┼─────────────────────────┼──────────┼─────────────────────────────┤
  │ 美国对华关 │                                          │ USTR官网（ustr.gov）人  │ 按事件驱 │                             │
  │ 税税率     │ 301条款加征关税产品清单及税率变化        │ 工记录关键节点 、PIIE   │ 动       │ 关税冲击模拟的基础数据      │
  │            │                                          │ 公开数据集（piie.com）  │          │                             │
  ├────────────┼──────────────────────────────────────────┼─────────────────────────┼──────────┼─────────────────────────────┤
  │ 集装箱运价 │ SCFI（上海出口集装箱运价指数）、CCFI（中 │ 上海航运交易所          │ 周度→季  │ 补充中欧/中美贸易运输成本指 │
  │ 指数       │ 国出口集装箱运价指数）                   │ 、AKShare 部分指数接口  │ 度均值   │ 标                          │
  └────────────┴──────────────────────────────────────────┴─────────────────────────┴──────────┴─────────────────────────────┘

  ---
  数据采集优先级建议

  根据可行性和对模型的贡献度排序：

  1. 高优先级（立即可获取，零门槛）：AKShare 财报/行情/宏观 — 这是整个模型的基础
  2. 中优先级（需要积分或注册）：Tushare Pro 部分数据、新闻爬虫
  3. 低优先级（需手工整理或爬取）：供应链关系（年报PDF解析）、关税历史节点

  关键提醒：AKShare 是目前国内金融数据采集最友好的免费接口，覆盖了文档中绝大多数需求，且无需申请积分。Tushare Pro
  作为补充（尤其新闻接口更稳定），但需要注册并积累积分。建议优先以 AKShare 为主数据源启动。

### 1. 资产负债表

In [20]:
import pandas as pd
import numpy as np
import akshare as ak
df_balance = ak.stock_balance_sheet_by_report_em(symbol="SH600519")
df_balance["REPORT_DATE"] = pd.to_datetime(df_balance["REPORT_DATE"])
df_balance.head()

  0%|          | 0/21 [00:00<?, ?it/s]

,SECUCODE,SECURITY_CODE,SECURITY_NAME_ABBR,ORG_CODE,ORG_TYPE,REPORT_DATE,REPORT_TYPE,REPORT_DATE_NAME,SECURITY_TYPE_CODE,NOTICE_DATE,...,TRADE_FINASSET_YOY,TRADE_FINLIAB_NOTFVTPL_YOY,TRADE_FINLIAB_YOY,TREASURY_SHARES_YOY,UNASSIGN_RPOFIT_YOY,UNCONFIRM_INVEST_LOSS_YOY,USERIGHT_ASSET_YOY,OPINION_TYPE,OSOPINION_TYPE,LISTING_STATE
0,600519.SH,600519,贵州茅台,10002602,通用,2026-03-31,一季报,2026一季报,058001001,2026-04-25 00:00:00,...,NaN,NaN,NaN,-30.440211,4.537781,NaN,-11.728702,NaN,NaN,0
1,600519.SH,600519,贵州茅台,10002602,通用,2025-12-31,年报,2025年报,058001001,2026-04-17 00:00:00,...,NaN,NaN,NaN,NaN,4.988163,NaN,-45.995769,标准无保留意见,NaN,0
2,600519.SH,600519,贵州茅台,10002602,通用,2025-09-30,三季报,2025三季报,058001001,2025-10-30 00:00:00,...,NaN,NaN,NaN,NaN,9.316275,NaN,-25.307840,NaN,NaN,0
3,600519.SH,600519,贵州茅台,10002602,通用,2025-06-30,中报,2025中报,058001001,2025-08-13 00:00:00,...,NaN,NaN,NaN,NaN,10.289127,NaN,-22.589532,NaN,NaN,0
4,600519.SH,600519,贵州茅台,10002602,通用,2025-03-31,一季报,2025一季报,058001001,2025-04-30 00:00:00,...,NaN,NaN,NaN,NaN,6.387490,NaN,-17.160585,NaN,NaN,0

In [21]:
balance_column = df_balance.columns.tolist()
print(balance_column)

['SECUCODE', 'SECURITY_CODE', 'SECURITY_NAME_ABBR', 'ORG_CODE', 'ORG_TYPE', 'REPORT_DATE', 'REPORT_TYPE', 'REPORT_DATE_NAME', 'SECURITY_TYPE_CODE', 'NOTICE_DATE', 'UPDATE_DATE', 'CURRENCY', 'ACCEPT_DEPOSIT_INTERBANK', 'ACCOUNTS_PAYABLE', 'ACCOUNTS_RECE', 'ACCRUED_EXPENSE', 'ADVANCE_RECEIVABLES', 'AGENT_TRADE_SECURITY', 'AGENT_UNDERWRITE_SECURITY', 'AMORTIZE_COST_FINASSET', 'AMORTIZE_COST_FINLIAB', 'AMORTIZE_COST_NCFINASSET', 'AMORTIZE_COST_NCFINLIAB', 'APPOINT_FVTPL_FINASSET', 'APPOINT_FVTPL_FINLIAB', 'ASSET_BALANCE', 'ASSET_OTHER', 'ASSIGN_CASH_DIVIDEND', 'AVAILABLE_SALE_FINASSET', 'BOND_PAYABLE', 'BORROW_FUND', 'BUY_RESALE_FINASSET', 'CAPITAL_RESERVE', 'CIP', 'CONSUMPTIVE_BIOLOGICAL_ASSET', 'CONTRACT_ASSET', 'CONTRACT_LIAB', 'CONVERT_DIFF', 'CREDITOR_INVEST', 'CURRENT_ASSET_BALANCE', 'CURRENT_ASSET_OTHER', 'CURRENT_LIAB_BALANCE', 'CURRENT_LIAB_OTHER', 'DEFER_INCOME', 'DEFER_INCOME_1YEAR', 'DEFER_TAX_ASSET', 'DEFER_TAX_LIAB', 'DERIVE_FINASSET', 'DERIVE_FINLIAB', 'DEVELOP_EXPENSE', 'DIV_HOLDSALE_ASSET', 'DIV_HOLDSALE_LIAB', 'DIVIDEND_PAYABLE', 'DIVIDEND_RECE', 'EQUITY_BALANCE', 'EQUITY_OTHER', 'EXPORT_REFUND_RECE', 'FEE_COMMISSION_PAYABLE', 'FIN_FUND', 'FINANCE_RECE', 'FIXED_ASSET', 'FIXED_ASSET_DISPOSAL', 'FVTOCI_FINASSET', 'FVTOCI_NCFINASSET', 'FVTPL_FINASSET', 'FVTPL_FINLIAB', 'GENERAL_RISK_RESERVE', 'GOODWILL', 'HOLD_MATURITY_INVEST', 'HOLDSALE_ASSET', 'HOLDSALE_LIAB', 'INSURANCE_CONTRACT_RESERVE', 'INTANGIBLE_ASSET', 'INTEREST_PAYABLE', 'INTEREST_RECE', 'INTERNAL_PAYABLE', 'INTERNAL_RECE', 'INVENTORY', 'INVEST_REALESTATE', 'LEASE_LIAB', 'LEND_FUND', 'LIAB_BALANCE', 'LIAB_EQUITY_BALANCE', 'LIAB_EQUITY_OTHER', 'LIAB_OTHER', 'LOAN_ADVANCE', 'LOAN_PBC', 'LONG_EQUITY_INVEST', 'LONG_LOAN', 'LONG_PAYABLE', 'LONG_PREPAID_EXPENSE', 'LONG_RECE', 'LONG_STAFFSALARY_PAYABLE', 'MINORITY_EQUITY', 'MONETARYFUNDS', 'NONCURRENT_ASSET_1YEAR', 'NONCURRENT_ASSET_BALANCE', 'NONCURRENT_ASSET_OTHER', 'NONCURRENT_LIAB_1YEAR', 'NONCURRENT_LIAB_BALANCE', 'NONCURRENT_LIAB_OTHER', 'NOTE_ACCOUNTS_PAYABLE', 'NOTE_ACCOUNTS_RECE', 'NOTE_PAYABLE', 'NOTE_RECE', 'OIL_GAS_ASSET', 'OTHER_COMPRE_INCOME', 'OTHER_CREDITOR_INVEST', 'OTHER_CURRENT_ASSET', 'OTHER_CURRENT_LIAB', 'OTHER_EQUITY_INVEST', 'OTHER_EQUITY_OTHER', 'OTHER_EQUITY_TOOL', 'OTHER_NONCURRENT_ASSET', 'OTHER_NONCURRENT_FINASSET', 'OTHER_NONCURRENT_LIAB', 'OTHER_PAYABLE', 'OTHER_RECE', 'PARENT_EQUITY_BALANCE', 'PARENT_EQUITY_OTHER', 'PERPETUAL_BOND', 'PERPETUAL_BOND_PAYBALE', 'PREDICT_CURRENT_LIAB', 'PREDICT_LIAB', 'PREFERRED_SHARES', 'PREFERRED_SHARES_PAYBALE', 'PREMIUM_RECE', 'PREPAYMENT', 'PRODUCTIVE_BIOLOGY_ASSET', 'PROJECT_MATERIAL', 'RC_RESERVE_RECE', 'REINSURE_PAYABLE', 'REINSURE_RECE', 'SELL_REPO_FINASSET', 'SETTLE_EXCESS_RESERVE', 'SHARE_CAPITAL', 'SHORT_BOND_PAYABLE', 'SHORT_FIN_PAYABLE', 'SHORT_LOAN', 'SPECIAL_PAYABLE', 'SPECIAL_RESERVE', 'STAFF_SALARY_PAYABLE', 'SUBSIDY_RECE', 'SURPLUS_RESERVE', 'TAX_PAYABLE', 'TOTAL_ASSETS', 'TOTAL_CURRENT_ASSETS', 'TOTAL_CURRENT_LIAB', 'TOTAL_EQUITY', 'TOTAL_LIAB_EQUITY', 'TOTAL_LIABILITIES', 'TOTAL_NONCURRENT_ASSETS', 'TOTAL_NONCURRENT_LIAB', 'TOTAL_OTHER_PAYABLE', 'TOTAL_OTHER_RECE', 'TOTAL_PARENT_EQUITY', 'TRADE_FINASSET', 'TRADE_FINASSET_NOTFVTPL', 'TRADE_FINLIAB', 'TRADE_FINLIAB_NOTFVTPL', 'TREASURY_SHARES', 'UNASSIGN_RPOFIT', 'UNCONFIRM_INVEST_LOSS', 'USERIGHT_ASSET', 'ACCEPT_DEPOSIT_INTERBANK_YOY', 'ACCOUNTS_PAYABLE_YOY', 'ACCOUNTS_RECE_YOY', 'ACCRUED_EXPENSE_YOY', 'ADVANCE_RECEIVABLES_YOY', 'AGENT_TRADE_SECURITY_YOY', 'AGENT_UNDERWRITE_SECURITY_YOY', 'AMORTIZE_COST_FINASSET_YOY', 'AMORTIZE_COST_FINLIAB_YOY', 'AMORTIZE_COST_NCFINASSET_YOY', 'AMORTIZE_COST_NCFINLIAB_YOY', 'APPOINT_FVTPL_FINASSET_YOY', 'APPOINT_FVTPL_FINLIAB_YOY', 'ASSET_BALANCE_YOY', 'ASSET_OTHER_YOY', 'ASSIGN_CASH_DIVIDEND_YOY', 'AVAILABLE_SALE_FINASSET_YOY', 'BOND_PAYABLE_YOY', 'BORROW_FUND_YOY', 'BUY_RESALE_FINASSET_YOY', 'CAPITAL_RESERVE_YOY', 'CIP_YOY', 'CONSUMPTIVE_BIOLOGICAL_ASSET_YOY', 'CONTRACT_ASSET_YOY', 'CONTRACT_LIAB_YOY', 'CONVERT_DIFF_YOY', 'CREDITOR_INVEST_YOY', 'CURRENT_ASSET_BALANCE_YOY', 'CURRENT_ASSET_OTHER_YOY', 'CURRENT_LIAB_BALANCE_YOY', 'CURRENT_LIAB_OTHER_YOY', 'DEFER_INCOME_1YEAR_YOY', 'DEFER_INCOME_YOY', 'DEFER_TAX_ASSET_YOY', 'DEFER_TAX_LIAB_YOY', 'DERIVE_FINASSET_YOY', 'DERIVE_FINLIAB_YOY', 'DEVELOP_EXPENSE_YOY', 'DIV_HOLDSALE_ASSET_YOY', 'DIV_HOLDSALE_LIAB_YOY', 'DIVIDEND_PAYABLE_YOY', 'DIVIDEND_RECE_YOY', 'EQUITY_BALANCE_YOY', 'EQUITY_OTHER_YOY', 'EXPORT_REFUND_RECE_YOY', 'FEE_COMMISSION_PAYABLE_YOY', 'FIN_FUND_YOY', 'FINANCE_RECE_YOY', 'FIXED_ASSET_DISPOSAL_YOY', 'FIXED_ASSET_YOY', 'FVTOCI_FINASSET_YOY', 'FVTOCI_NCFINASSET_YOY', 'FVTPL_FINASSET_YOY', 'FVTPL_FINLIAB_YOY', 'GENERAL_RISK_RESERVE_YOY', 'GOODWILL_YOY', 'HOLD_MATURITY_INVEST_YOY', 'HOLDSALE_ASSET_YOY', 'HOLDSALE_LIAB_YOY', 'INSURANCE_CONTRACT_RESERVE_YOY', 'INTANGIBLE_ASSET_YOY', 'INTEREST_PAYABLE_YOY', 'INTEREST_RECE_YOY', 'INTERNAL_PAYABLE_YOY', 'INTERNAL_RECE_YOY', 'INVENTORY_YOY', 'INVEST_REALESTATE_YOY', 'LEASE_LIAB_YOY', 'LEND_FUND_YOY', 'LIAB_BALANCE_YOY', 'LIAB_EQUITY_BALANCE_YOY', 'LIAB_EQUITY_OTHER_YOY', 'LIAB_OTHER_YOY', 'LOAN_ADVANCE_YOY', 'LOAN_PBC_YOY', 'LONG_EQUITY_INVEST_YOY', 'LONG_LOAN_YOY', 'LONG_PAYABLE_YOY', 'LONG_PREPAID_EXPENSE_YOY', 'LONG_RECE_YOY', 'LONG_STAFFSALARY_PAYABLE_YOY', 'MINORITY_EQUITY_YOY', 'MONETARYFUNDS_YOY', 'NONCURRENT_ASSET_1YEAR_YOY', 'NONCURRENT_ASSET_BALANCE_YOY', 'NONCURRENT_ASSET_OTHER_YOY', 'NONCURRENT_LIAB_1YEAR_YOY', 'NONCURRENT_LIAB_BALANCE_YOY', 'NONCURRENT_LIAB_OTHER_YOY', 'NOTE_ACCOUNTS_PAYABLE_YOY', 'NOTE_ACCOUNTS_RECE_YOY', 'NOTE_PAYABLE_YOY', 'NOTE_RECE_YOY', 'OIL_GAS_ASSET_YOY', 'OTHER_COMPRE_INCOME_YOY', 'OTHER_CREDITOR_INVEST_YOY', 'OTHER_CURRENT_ASSET_YOY', 'OTHER_CURRENT_LIAB_YOY', 'OTHER_EQUITY_INVEST_YOY', 'OTHER_EQUITY_OTHER_YOY', 'OTHER_EQUITY_TOOL_YOY', 'OTHER_NONCURRENT_ASSET_YOY', 'OTHER_NONCURRENT_FINASSET_YOY', 'OTHER_NONCURRENT_LIAB_YOY', 'OTHER_PAYABLE_YOY', 'OTHER_RECE_YOY', 'PARENT_EQUITY_BALANCE_YOY', 'PARENT_EQUITY_OTHER_YOY', 'PERPETUAL_BOND_PAYBALE_YOY', 'PERPETUAL_BOND_YOY', 'PREDICT_CURRENT_LIAB_YOY', 'PREDICT_LIAB_YOY', 'PREFERRED_SHARES_PAYBALE_YOY', 'PREFERRED_SHARES_YOY', 'PREMIUM_RECE_YOY', 'PREPAYMENT_YOY', 'PRODUCTIVE_BIOLOGY_ASSET_YOY', 'PROJECT_MATERIAL_YOY', 'RC_RESERVE_RECE_YOY', 'REINSURE_PAYABLE_YOY', 'REINSURE_RECE_YOY', 'SELL_REPO_FINASSET_YOY', 'SETTLE_EXCESS_RESERVE_YOY', 'SHARE_CAPITAL_YOY', 'SHORT_BOND_PAYABLE_YOY', 'SHORT_FIN_PAYABLE_YOY', 'SHORT_LOAN_YOY', 'SPECIAL_PAYABLE_YOY', 'SPECIAL_RESERVE_YOY', 'STAFF_SALARY_PAYABLE_YOY', 'SUBSIDY_RECE_YOY', 'SURPLUS_RESERVE_YOY', 'TAX_PAYABLE_YOY', 'TOTAL_ASSETS_YOY', 'TOTAL_CURRENT_ASSETS_YOY', 'TOTAL_CURRENT_LIAB_YOY', 'TOTAL_EQUITY_YOY', 'TOTAL_LIAB_EQUITY_YOY', 'TOTAL_LIABILITIES_YOY', 'TOTAL_NONCURRENT_ASSETS_YOY', 'TOTAL_NONCURRENT_LIAB_YOY', 'TOTAL_OTHER_PAYABLE_YOY', 'TOTAL_OTHER_RECE_YOY', 'TOTAL_PARENT_EQUITY_YOY', 'TRADE_FINASSET_NOTFVTPL_YOY', 'TRADE_FINASSET_YOY', 'TRADE_FINLIAB_NOTFVTPL_YOY', 'TRADE_FINLIAB_YOY', 'TREASURY_SHARES_YOY', 'UNASSIGN_RPOFIT_YOY', 'UNCONFIRM_INVEST_LOSS_YOY', 'USERIGHT_ASSET_YOY', 'OPINION_TYPE', 'OSOPINION_TYPE', 'LISTING_STATE']

In [37]:
selected_balance_columns = ["REPORT_DATE","TOTAL_ASSETS", "TOTAL_LIABILITIES", "TOTAL_EQUITY", "TOTAL_PARENT_EQUITY",
    "TOTAL_CURRENT_ASSETS", "TOTAL_CURRENT_LIAB", "MONETARYFUNDS", "INVENTORY",
    "ACCOUNTS_RECE", "SHORT_LOAN", "LONG_LOAN", "TOTAL_NONCURRENT_ASSETS",
    "TOTAL_NONCURRENT_LIAB", "FIXED_ASSET", "INTANGIBLE_ASSET", "GOODWILL",
    "LONG_EQUITY_INVEST", "CIP", "PREPAYMENT", "CONTRACT_ASSET", "CONTRACT_LIAB",
    "ADVANCE_RECEIVABLES", "ACCOUNTS_PAYABLE", "MINORITY_EQUITY", "DEFER_TAX_ASSET",
    "DEFER_TAX_LIAB", "LEASE_LIAB", "USERIGHT_ASSET", "DEVELOP_EXPENSE",
    "TREASURY_SHARES", "SHARE_CAPITAL", "CAPITAL_RESERVE", "SURPLUS_RESERVE",
    "UNASSIGN_RPOFIT", "OTHER_RECE", "OTHER_PAYABLE", "INTEREST_RECE",
    "INTEREST_PAYABLE", "BOND_PAYABLE", "NOTE_ACCOUNTS_RECE"
]

df_balance = df_balance[selected_balance_columns]
df_balance

,REPORT_DATE,TOTAL_ASSETS,TOTAL_LIABILITIES,TOTAL_EQUITY,TOTAL_PARENT_EQUITY,TOTAL_CURRENT_ASSETS,TOTAL_CURRENT_LIAB,MONETARYFUNDS,INVENTORY,ACCOUNTS_RECE,...,SHARE_CAPITAL,CAPITAL_RESERVE,SURPLUS_RESERVE,UNASSIGN_RPOFIT,OTHER_RECE,OTHER_PAYABLE,INTEREST_RECE,INTEREST_PAYABLE,BOND_PAYABLE,NOTE_ACCOUNTS_RECE
0,2026-03-31,3.199188e+11,3.878296e+10,2.811359e+11,2.708940e+11,2.715245e+11,3.845559e+10,4.878669e+10,6.069232e+10,32344588.37,...,1.252270e+09,1.577095e+06,5.054318e+10,2.191477e+11,NaN,NaN,NaN,NaN,NaN,3.234459e+07
1,2025-12-31,3.038348e+11,4.987559e+10,2.539593e+11,2.446378e+11,2.525187e+11,4.961048e+10,5.169061e+10,6.142742e+10,2609048.49,...,1.252270e+09,1.577095e+06,5.054318e+10,1.919051e+11,NaN,NaN,NaN,NaN,NaN,2.609048e+06
2,2025-09-30,3.047382e+11,3.903316e+10,2.657050e+11,2.570700e+11,2.565872e+11,3.876338e+10,5.175306e+10,5.585886e+10,25531737.62,...,1.256198e+09,1.374964e+09,4.850378e+10,2.108750e+11,NaN,NaN,NaN,NaN,NaN,5.235062e+09
3,2025-06-30,2.922578e+11,4.312220e+10,2.491356e+11,2.386465e+11,2.454784e+11,4.284285e+10,5.164488e+10,5.497173e+10,37961242.39,...,1.256198e+09,1.374964e+09,4.850378e+10,1.916512e+11,NaN,NaN,NaN,NaN,NaN,2.853742e+09
4,2025-03-31,3.123687e+11,4.417836e+10,2.681903e+11,2.583578e+11,2.665067e+11,4.387018e+10,5.219924e+10,5.479846e+10,15199312.09,...,1.256198e+09,1.374964e+09,4.663579e+10,2.096349e+11,NaN,NaN,NaN,NaN,NaN,2.142659e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,2001-12-31,3.463389e+09,9.257570e+08,2.537632e+09,2.530916e+09,2.869925e+09,9.257570e+08,1.956437e+09,7.863688e+08,46700450.37,...,2.500000e+08,2.039190e+09,1.636125e+08,7.811364e+07,33320706.81,1.766921e+08,NaN,NaN,NaN,5.844045e+07
98,2001-06-30,1.214455e+09,6.424918e+08,5.615454e+08,5.615454e+08,1.011106e+09,6.424918e+08,3.364392e+08,5.755478e+08,41891812.09,...,1.850000e+08,8.947032e+07,1.147347e+08,1.723404e+08,12708576.89,6.106470e+07,NaN,NaN,NaN,7.304643e+07
99,2000-12-31,1.268856e+09,8.250766e+08,4.437796e+08,4.424207e+08,1.069970e+09,8.250766e+08,4.609836e+08,5.123328e+08,47884805.68,...,1.850000e+08,8.843268e+07,6.343543e+07,1.055526e+08,9792294.12,1.055809e+08,NaN,NaN,NaN,5.038481e+07
100,1999-12-31,9.150570e+08,6.296951e+08,2.853619e+08,2.853619e+08,7.200793e+08,6.296951e+08,1.983906e+08,4.234011e+08,NaN,...,1.850000e+08,8.843268e+07,6.166053e+06,5.763120e+06,NaN,5.902493e+07,NaN,NaN,NaN,1.341220e+07
101,1998-12-31,7.418490e+08,5.077575e+08,2.340915e+08,2.340915e+08,5.209076e+08,4.473975e+08,1.247654e+08,3.166659e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,1.861318e+07,NaN,NaN,NaN,NaN

### 2. 利润表

In [25]:
df_income = ak.stock_profit_sheet_by_report_em(symbol="SH600519")
df_income

  0%|          | 0/21 [00:00<?, ?it/s]

,SECUCODE,SECURITY_CODE,SECURITY_NAME_ABBR,ORG_CODE,ORG_TYPE,REPORT_DATE,REPORT_TYPE,REPORT_DATE_NAME,SECURITY_TYPE_CODE,NOTICE_DATE,...,PRECOMBINE_TCI_YOY,EFFECT_TCI_BALANCE,EFFECT_TCI_BALANCE_YOY,TCI_OTHER,TCI_OTHER_YOY,TCI_BALANCE,TCI_BALANCE_YOY,ACF_END_INCOME,ACF_END_INCOME_YOY,OPINION_TYPE
0,600519.SH,600519,贵州茅台,10002602,通用,2026-03-31 00:00:00,一季报,2026一季报,058001001,2026-04-25 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,600519.SH,600519,贵州茅台,10002602,通用,2025-12-31 00:00:00,年报,2025年报,058001001,2026-04-17 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,标准无保留意见
2,600519.SH,600519,贵州茅台,10002602,通用,2025-09-30 00:00:00,三季报,2025三季报,058001001,2025-10-30 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,600519.SH,600519,贵州茅台,10002602,通用,2025-06-30 00:00:00,中报,2025中报,058001001,2025-08-13 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,600519.SH,600519,贵州茅台,10002602,通用,2025-03-31 00:00:00,一季报,2025一季报,058001001,2025-04-30 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,600519.SH,600519,贵州茅台,10002602,通用,2001-12-31 00:00:00,年报,2001年报,058001001,2003-03-26 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,标准无保留意见
98,600519.SH,600519,贵州茅台,10002602,通用,2001-06-30 00:00:00,中报,2001中报,058001001,2002-08-14 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,标准无保留意见
99,600519.SH,600519,贵州茅台,10002602,通用,2000-12-31 00:00:00,年报,2000年报,058001001,2002-04-17 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,标准无保留意见
100,600519.SH,600519,贵州茅台,10002602,通用,1999-12-31 00:00:00,年报,1999年报,058001001,2001-07-26 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,标准无保留意见
101,600519.SH,600519,贵州茅台,10002602,通用,1998-12-31 00:00:00,年报,1998年报,058001001,2001-07-26 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,标准无保留意见

In [27]:
income_column = df_income.columns.tolist()
print(income_column)

['SECUCODE', 'SECURITY_CODE', 'SECURITY_NAME_ABBR', 'ORG_CODE', 'ORG_TYPE', 'REPORT_DATE', 'REPORT_TYPE', 'REPORT_DATE_NAME', 'SECURITY_TYPE_CODE', 'NOTICE_DATE', 'UPDATE_DATE', 'CURRENCY', 'TOTAL_OPERATE_INCOME', 'TOTAL_OPERATE_INCOME_YOY', 'OPERATE_INCOME', 'OPERATE_INCOME_YOY', 'INTEREST_INCOME', 'INTEREST_INCOME_YOY', 'EARNED_PREMIUM', 'EARNED_PREMIUM_YOY', 'FEE_COMMISSION_INCOME', 'FEE_COMMISSION_INCOME_YOY', 'OTHER_BUSINESS_INCOME', 'OTHER_BUSINESS_INCOME_YOY', 'TOI_OTHER', 'TOI_OTHER_YOY', 'TOTAL_OPERATE_COST', 'TOTAL_OPERATE_COST_YOY', 'OPERATE_COST', 'OPERATE_COST_YOY', 'INTEREST_EXPENSE', 'INTEREST_EXPENSE_YOY', 'FEE_COMMISSION_EXPENSE', 'FEE_COMMISSION_EXPENSE_YOY', 'RESEARCH_EXPENSE', 'RESEARCH_EXPENSE_YOY', 'SURRENDER_VALUE', 'SURRENDER_VALUE_YOY', 'NET_COMPENSATE_EXPENSE', 'NET_COMPENSATE_EXPENSE_YOY', 'NET_CONTRACT_RESERVE', 'NET_CONTRACT_RESERVE_YOY', 'POLICY_BONUS_EXPENSE', 'POLICY_BONUS_EXPENSE_YOY', 'REINSURE_EXPENSE', 'REINSURE_EXPENSE_YOY', 'OTHER_BUSINESS_COST', 'OTHER_BUSINESS_COST_YOY', 'OPERATE_TAX_ADD', 'OPERATE_TAX_ADD_YOY', 'SALE_EXPENSE', 'SALE_EXPENSE_YOY', 'MANAGE_EXPENSE', 'MANAGE_EXPENSE_YOY', 'ME_RESEARCH_EXPENSE', 'ME_RESEARCH_EXPENSE_YOY', 'FINANCE_EXPENSE', 'FINANCE_EXPENSE_YOY', 'FE_INTEREST_EXPENSE', 'FE_INTEREST_EXPENSE_YOY', 'FE_INTEREST_INCOME', 'FE_INTEREST_INCOME_YOY', 'ASSET_IMPAIRMENT_LOSS', 'ASSET_IMPAIRMENT_LOSS_YOY', 'CREDIT_IMPAIRMENT_LOSS', 'CREDIT_IMPAIRMENT_LOSS_YOY', 'TOC_OTHER', 'TOC_OTHER_YOY', 'FAIRVALUE_CHANGE_INCOME', 'FAIRVALUE_CHANGE_INCOME_YOY', 'INVEST_INCOME', 'INVEST_INCOME_YOY', 'INVEST_JOINT_INCOME', 'INVEST_JOINT_INCOME_YOY', 'NET_EXPOSURE_INCOME', 'NET_EXPOSURE_INCOME_YOY', 'EXCHANGE_INCOME', 'EXCHANGE_INCOME_YOY', 'ASSET_DISPOSAL_INCOME', 'ASSET_DISPOSAL_INCOME_YOY', 'ASSET_IMPAIRMENT_INCOME', 'ASSET_IMPAIRMENT_INCOME_YOY', 'CREDIT_IMPAIRMENT_INCOME', 'CREDIT_IMPAIRMENT_INCOME_YOY', 'OTHER_INCOME', 'OTHER_INCOME_YOY', 'OPERATE_PROFIT_OTHER', 'OPERATE_PROFIT_OTHER_YOY', 'OPERATE_PROFIT_BALANCE', 'OPERATE_PROFIT_BALANCE_YOY', 'OPERATE_PROFIT', 'OPERATE_PROFIT_YOY', 'NONBUSINESS_INCOME', 'NONBUSINESS_INCOME_YOY', 'NONCURRENT_DISPOSAL_INCOME', 'NONCURRENT_DISPOSAL_INCOME_YOY', 'NONBUSINESS_EXPENSE', 'NONBUSINESS_EXPENSE_YOY', 'NONCURRENT_DISPOSAL_LOSS', 'NONCURRENT_DISPOSAL_LOSS_YOY', 'EFFECT_TP_OTHER', 'EFFECT_TP_OTHER_YOY', 'TOTAL_PROFIT_BALANCE', 'TOTAL_PROFIT_BALANCE_YOY', 'TOTAL_PROFIT', 'TOTAL_PROFIT_YOY', 'INCOME_TAX', 'INCOME_TAX_YOY', 'EFFECT_NETPROFIT_OTHER', 'EFFECT_NETPROFIT_OTHER_YOY', 'EFFECT_NETPROFIT_BALANCE', 'EFFECT_NETPROFIT_BALANCE_YOY', 'UNCONFIRM_INVEST_LOSS', 'UNCONFIRM_INVEST_LOSS_YOY', 'NETPROFIT', 'NETPROFIT_YOY', 'PRECOMBINE_PROFIT', 'PRECOMBINE_PROFIT_YOY', 'CONTINUED_NETPROFIT', 'CONTINUED_NETPROFIT_YOY', 'DISCONTINUED_NETPROFIT', 'DISCONTINUED_NETPROFIT_YOY', 'PARENT_NETPROFIT', 'PARENT_NETPROFIT_YOY', 'MINORITY_INTEREST', 'MINORITY_INTEREST_YOY', 'DEDUCT_PARENT_NETPROFIT', 'DEDUCT_PARENT_NETPROFIT_YOY', 'NETPROFIT_OTHER', 'NETPROFIT_OTHER_YOY', 'NETPROFIT_BALANCE', 'NETPROFIT_BALANCE_YOY', 'BASIC_EPS', 'BASIC_EPS_YOY', 'DILUTED_EPS', 'DILUTED_EPS_YOY', 'OTHER_COMPRE_INCOME', 'OTHER_COMPRE_INCOME_YOY', 'PARENT_OCI', 'PARENT_OCI_YOY', 'MINORITY_OCI', 'MINORITY_OCI_YOY', 'PARENT_OCI_OTHER', 'PARENT_OCI_OTHER_YOY', 'PARENT_OCI_BALANCE', 'PARENT_OCI_BALANCE_YOY', 'UNABLE_OCI', 'UNABLE_OCI_YOY', 'CREDITRISK_FAIRVALUE_CHANGE', 'CREDITRISK_FAIRVALUE_CHANGE_YOY', 'OTHERRIGHT_FAIRVALUE_CHANGE', 'OTHERRIGHT_FAIRVALUE_CHANGE_YOY', 'SETUP_PROFIT_CHANGE', 'SETUP_PROFIT_CHANGE_YOY', 'RIGHTLAW_UNABLE_OCI', 'RIGHTLAW_UNABLE_OCI_YOY', 'UNABLE_OCI_OTHER', 'UNABLE_OCI_OTHER_YOY', 'UNABLE_OCI_BALANCE', 'UNABLE_OCI_BALANCE_YOY', 'ABLE_OCI', 'ABLE_OCI_YOY', 'RIGHTLAW_ABLE_OCI', 'RIGHTLAW_ABLE_OCI_YOY', 'AFA_FAIRVALUE_CHANGE', 'AFA_FAIRVALUE_CHANGE_YOY', 'HMI_AFA', 'HMI_AFA_YOY', 'CASHFLOW_HEDGE_VALID', 'CASHFLOW_HEDGE_VALID_YOY', 'CREDITOR_FAIRVALUE_CHANGE', 'CREDITOR_FAIRVALUE_CHANGE_YOY', 'CREDITOR_IMPAIRMENT_RESERVE', 'CREDITOR_IMPAIRMENT_RESERVE_YOY', 'FINANCE_OCI_AMT', 'FINANCE_OCI_AMT_YOY', 'CONVERT_DIFF', 'CONVERT_DIFF_YOY', 'ABLE_OCI_OTHER', 'ABLE_OCI_OTHER_YOY', 'ABLE_OCI_BALANCE', 'ABLE_OCI_BALANCE_YOY', 'OCI_OTHER', 'OCI_OTHER_YOY', 'OCI_BALANCE', 'OCI_BALANCE_YOY', 'TOTAL_COMPRE_INCOME', 'TOTAL_COMPRE_INCOME_YOY', 'PARENT_TCI', 'PARENT_TCI_YOY', 'MINORITY_TCI', 'MINORITY_TCI_YOY', 'PRECOMBINE_TCI', 'PRECOMBINE_TCI_YOY', 'EFFECT_TCI_BALANCE', 'EFFECT_TCI_BALANCE_YOY', 'TCI_OTHER', 'TCI_OTHER_YOY', 'TCI_BALANCE', 'TCI_BALANCE_YOY', 'ACF_END_INCOME', 'ACF_END_INCOME_YOY', 'OPINION_TYPE']

In [30]:
# 利润表TRACE项目核心32字段（不含YOY预计算列）
selected_income_columns = [
    "REPORT_DATE",
    # 核心收入利润列 (10列)
    "TOTAL_OPERATE_INCOME",
    "OPERATE_INCOME",
    "TOTAL_OPERATE_COST",
    "OPERATE_COST",
    "OPERATE_PROFIT",
    "TOTAL_PROFIT",
    "NETPROFIT",
    "PARENT_NETPROFIT",
    "DEDUCT_PARENT_NETPROFIT",
    "BASIC_EPS",
    
    # 费用结构列 (9列)
    "SALE_EXPENSE",
    "MANAGE_EXPENSE",
    "RESEARCH_EXPENSE",
    "FINANCE_EXPENSE",
    "FE_INTEREST_EXPENSE",
    "FE_INTEREST_INCOME",
    "OPERATE_TAX_ADD",
    "ASSET_IMPAIRMENT_LOSS",
    "CREDIT_IMPAIRMENT_LOSS",
    
    # 非经常性损益列 (8列)
    "INVEST_INCOME",
    "INVEST_JOINT_INCOME",
    "FAIRVALUE_CHANGE_INCOME",
    "ASSET_DISPOSAL_INCOME",
    "NONBUSINESS_INCOME",
    "NONBUSINESS_EXPENSE",
    "EXCHANGE_INCOME",
    "OTHER_INCOME",
    
    # 利润质量+口径检查列 (5列)
    "CONTINUED_NETPROFIT",
    "DISCONTINUED_NETPROFIT",
    "MINORITY_INTEREST",
    "INCOME_TAX",
    "TOTAL_COMPRE_INCOME"
]

df_income = df_income[selected_income_columns]
df_income

,REPORT_DATE,TOTAL_OPERATE_INCOME,OPERATE_INCOME,TOTAL_OPERATE_COST,OPERATE_COST,OPERATE_PROFIT,TOTAL_PROFIT,NETPROFIT,PARENT_NETPROFIT,DEDUCT_PARENT_NETPROFIT,...,ASSET_DISPOSAL_INCOME,NONBUSINESS_INCOME,NONBUSINESS_EXPENSE,EXCHANGE_INCOME,OTHER_INCOME,CONTINUED_NETPROFIT,DISCONTINUED_NETPROFIT,MINORITY_INTEREST,INCOME_TAX,TOTAL_COMPRE_INCOME
0,2026-03-31 00:00:00,5.470291e+10,5.390925e+10,1.719222e+10,5.520729e+09,3.753701e+10,3.754325e+10,2.815383e+10,2.724251e+10,2.723999e+10,...,130409.49,6759734.60,5.187770e+05,NaN,2970996.16,2.815383e+10,NaN,9.113186e+08,9.389418e+09,2.816871e+10
1,2025-12-31 00:00:00,1.720542e+11,1.688381e+11,5.737082e+10,1.489228e+10,1.148090e+11,1.147553e+11,8.531032e+10,8.232007e+10,8.229311e+10,...,3106625.19,74947039.70,1.286356e+08,NaN,28531529.30,8.531032e+10,NaN,2.990258e+09,2.944494e+10,8.531025e+10
2,2025-09-30 00:00:00,1.309039e+11,1.284537e+11,4.142615e+10,1.118397e+10,8.948969e+10,8.940344e+10,6.689880e+10,6.462675e+10,6.468062e+10,...,511925.45,39970046.24,1.262202e+08,NaN,24453342.83,6.689880e+10,NaN,2.272058e+09,2.250464e+10,6.690677e+10
3,2025-06-30 00:00:00,9.109376e+10,8.938935e+10,2.835395e+10,7.777491e+09,6.276897e+10,6.277800e+10,4.698668e+10,4.540296e+10,4.539025e+10,...,511925.45,32407899.24,2.338051e+07,NaN,22518010.95,4.698668e+10,NaN,1.583719e+09,1.579132e+10,4.699738e+10
4,2025-03-31 00:00:00,5.144345e+10,5.060096e+10,1.443330e+10,4.061431e+09,3.703660e+10,3.703145e+10,2.777464e+10,2.684747e+10,2.684988e+10,...,491793.53,16421712.88,2.156629e+07,NaN,17785942.53,2.777464e+10,NaN,9.271618e+08,9.256818e+09,2.777792e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,2001-12-31 00:00:00,1.618047e+09,1.618047e+09,1.009061e+09,2.875385e+08,6.101417e+08,6.072782e+08,3.423658e+08,3.282907e+08,3.348725e+08,...,NaN,72208.04,3.004335e+06,NaN,NaN,NaN,NaN,1.407509e+07,2.649124e+08,NaN
98,2001-06-30 00:00:00,8.738635e+08,8.738635e+08,5.012727e+08,1.464832e+08,3.735536e+08,3.729922e+08,2.300671e+08,2.234079e+08,NaN,...,NaN,51586.44,6.129969e+05,NaN,NaN,NaN,NaN,6.659118e+06,1.429251e+08,NaN
99,2000-12-31 00:00:00,1.114001e+09,1.114001e+09,6.672632e+08,1.968634e+08,4.457564e+08,4.448454e+08,2.552848e+08,2.495589e+08,NaN,...,NaN,17635.96,9.603751e+05,NaN,NaN,NaN,NaN,5.725934e+06,1.895606e+08,NaN
100,1999-12-31 00:00:00,8.908582e+08,8.908582e+08,5.375896e+08,1.291332e+08,3.536477e+08,3.535926e+08,2.156901e+08,2.156901e+08,NaN,...,NaN,1500.00,5.661431e+04,NaN,NaN,NaN,NaN,NaN,1.379025e+08,NaN
101,1998-12-31 00:00:00,6.281844e+08,6.281844e+08,4.102516e+08,7.672537e+07,2.189657e+08,2.189657e+08,1.468914e+08,1.468914e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.207430e+07,NaN

In [31]:
df_cashflow = ak.stock_cash_flow_sheet_by_report_em(symbol="SH600519")
df_cashflow

  0%|          | 0/20 [00:00<?, ?it/s]

,SECUCODE,SECURITY_CODE,SECURITY_NAME_ABBR,ORG_CODE,ORG_TYPE,REPORT_DATE,REPORT_TYPE,REPORT_DATE_NAME,SECURITY_TYPE_CODE,NOTICE_DATE,...,BEGIN_CASH_EQUIVALENTS_YOY,CCE_ADD_OTHERNOTE_YOY,CCE_ADD_BALANCENOTE_YOY,CCE_ADDNOTE_YOY,OPINION_TYPE,OSOPINION_TYPE,MINORITY_INTEREST,MINORITY_INTEREST_YOY,USERIGHT_ASSET_AMORTIZE,USERIGHT_ASSET_AMORTIZE_YOY
0,600519.SH,600519,贵州茅台,10002602,通用,2026-03-31 00:00:00,一季报,2026一季报,058001001,2026-04-25 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,600519.SH,600519,贵州茅台,10002602,通用,2025-12-31 00:00:00,年报,2025年报,058001001,2026-04-17 00:00:00,...,89.071333,NaN,NaN,-322.053550,标准无保留意见,NaN,NaN,NaN,55797324.89,-40.950637
2,600519.SH,600519,贵州茅台,10002602,通用,2025-09-30 00:00:00,三季报,2025三季报,058001001,2025-10-30 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,600519.SH,600519,贵州茅台,10002602,通用,2025-06-30 00:00:00,中报,2025中报,058001001,2025-08-13 00:00:00,...,89.071333,NaN,NaN,-431.766810,NaN,NaN,NaN,NaN,26052929.46,-24.478494
4,600519.SH,600519,贵州茅台,10002602,通用,2025-03-31 00:00:00,一季报,2025一季报,058001001,2025-04-30 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,600519.SH,600519,贵州茅台,10002602,通用,2002-12-31 00:00:00,年报,2002年报,058001001,2003-03-26 00:00:00,...,NaN,NaN,NaN,-111.777627,标准无保留意见,NaN,NaN,NaN,NaN,NaN
94,600519.SH,600519,贵州茅台,10002602,通用,2002-06-30 00:00:00,中报,2002中报,058001001,2002-08-14 00:00:00,...,NaN,NaN,100.0,-255.404488,未经审计,NaN,NaN,NaN,NaN,NaN
95,600519.SH,600519,贵州茅台,10002602,通用,2001-12-31 00:00:00,年报,2001年报,058001001,2002-04-17 00:00:00,...,NaN,NaN,NaN,469.494681,标准无保留意见,NaN,NaN,NaN,NaN,NaN
96,600519.SH,600519,贵州茅台,10002602,通用,2001-06-30 00:00:00,中报,2001中报,058001001,2001-08-22 00:00:00,...,NaN,NaN,NaN,NaN,标准无保留意见,NaN,NaN,NaN,NaN,NaN
97,600519.SH,600519,贵州茅台,10002602,通用,2000-12-31 00:00:00,年报,2000年报,058001001,2001-07-26 00:00:00,...,NaN,NaN,NaN,NaN,标准无保留意见,NaN,NaN,NaN,NaN,NaN

In [32]:
cashflow_column = df_cashflow.columns.tolist()
print(cashflow_column)

['SECUCODE', 'SECURITY_CODE', 'SECURITY_NAME_ABBR', 'ORG_CODE', 'ORG_TYPE', 'REPORT_DATE', 'REPORT_TYPE', 'REPORT_DATE_NAME', 'SECURITY_TYPE_CODE', 'NOTICE_DATE', 'UPDATE_DATE', 'CURRENCY', 'SALES_SERVICES', 'DEPOSIT_INTERBANK_ADD', 'LOAN_PBC_ADD', 'OFI_BF_ADD', 'RECEIVE_ORIGIC_PREMIUM', 'RECEIVE_REINSURE_NET', 'INSURED_INVEST_ADD', 'DISPOSAL_TFA_ADD', 'RECEIVE_INTEREST_COMMISSION', 'BORROW_FUND_ADD', 'LOAN_ADVANCE_REDUCE', 'REPO_BUSINESS_ADD', 'RECEIVE_TAX_REFUND', 'RECEIVE_OTHER_OPERATE', 'OPERATE_INFLOW_OTHER', 'OPERATE_INFLOW_BALANCE', 'TOTAL_OPERATE_INFLOW', 'BUY_SERVICES', 'LOAN_ADVANCE_ADD', 'PBC_INTERBANK_ADD', 'PAY_ORIGIC_COMPENSATE', 'PAY_INTEREST_COMMISSION', 'PAY_POLICY_BONUS', 'PAY_STAFF_CASH', 'PAY_ALL_TAX', 'PAY_OTHER_OPERATE', 'OPERATE_OUTFLOW_OTHER', 'OPERATE_OUTFLOW_BALANCE', 'TOTAL_OPERATE_OUTFLOW', 'OPERATE_NETCASH_OTHER', 'OPERATE_NETCASH_BALANCE', 'NETCASH_OPERATE', 'WITHDRAW_INVEST', 'RECEIVE_INVEST_INCOME', 'DISPOSAL_LONG_ASSET', 'DISPOSAL_SUBSIDIARY_OTHER', 'REDUCE_PLEDGE_TIMEDEPOSITS', 'RECEIVE_OTHER_INVEST', 'INVEST_INFLOW_OTHER', 'INVEST_INFLOW_BALANCE', 'TOTAL_INVEST_INFLOW', 'CONSTRUCT_LONG_ASSET', 'INVEST_PAY_CASH', 'PLEDGE_LOAN_ADD', 'OBTAIN_SUBSIDIARY_OTHER', 'ADD_PLEDGE_TIMEDEPOSITS', 'PAY_OTHER_INVEST', 'INVEST_OUTFLOW_OTHER', 'INVEST_OUTFLOW_BALANCE', 'TOTAL_INVEST_OUTFLOW', 'INVEST_NETCASH_OTHER', 'INVEST_NETCASH_BALANCE', 'NETCASH_INVEST', 'ACCEPT_INVEST_CASH', 'SUBSIDIARY_ACCEPT_INVEST', 'RECEIVE_LOAN_CASH', 'ISSUE_BOND', 'RECEIVE_OTHER_FINANCE', 'FINANCE_INFLOW_OTHER', 'FINANCE_INFLOW_BALANCE', 'TOTAL_FINANCE_INFLOW', 'PAY_DEBT_CASH', 'ASSIGN_DIVIDEND_PORFIT', 'SUBSIDIARY_PAY_DIVIDEND', 'BUY_SUBSIDIARY_EQUITY', 'PAY_OTHER_FINANCE', 'SUBSIDIARY_REDUCE_CASH', 'FINANCE_OUTFLOW_OTHER', 'FINANCE_OUTFLOW_BALANCE', 'TOTAL_FINANCE_OUTFLOW', 'FINANCE_NETCASH_OTHER', 'FINANCE_NETCASH_BALANCE', 'NETCASH_FINANCE', 'RATE_CHANGE_EFFECT', 'CCE_ADD_OTHER', 'CCE_ADD_BALANCE', 'CCE_ADD', 'BEGIN_CCE', 'END_CCE_OTHER', 'END_CCE_BALANCE', 'END_CCE', 'NETPROFIT', 'ASSET_IMPAIRMENT', 'FA_IR_DEPR', 'OILGAS_BIOLOGY_DEPR', 'IR_DEPR', 'IA_AMORTIZE', 'LPE_AMORTIZE', 'DEFER_INCOME_AMORTIZE', 'PREPAID_EXPENSE_REDUCE', 'ACCRUED_EXPENSE_ADD', 'DISPOSAL_LONGASSET_LOSS', 'FA_SCRAP_LOSS', 'FAIRVALUE_CHANGE_LOSS', 'FINANCE_EXPENSE', 'INVEST_LOSS', 'DEFER_TAX', 'DT_ASSET_REDUCE', 'DT_LIAB_ADD', 'PREDICT_LIAB_ADD', 'INVENTORY_REDUCE', 'OPERATE_RECE_REDUCE', 'OPERATE_PAYABLE_ADD', 'OTHER', 'OPERATE_NETCASH_OTHERNOTE', 'OPERATE_NETCASH_BALANCENOTE', 'NETCASH_OPERATENOTE', 'DEBT_TRANSFER_CAPITAL', 'CONVERT_BOND_1YEAR', 'FINLEASE_OBTAIN_FA', 'UNINVOLVE_INVESTFIN_OTHER', 'END_CASH', 'BEGIN_CASH', 'END_CASH_EQUIVALENTS', 'BEGIN_CASH_EQUIVALENTS', 'CCE_ADD_OTHERNOTE', 'CCE_ADD_BALANCENOTE', 'CCE_ADDNOTE', 'SALES_SERVICES_YOY', 'DEPOSIT_INTERBANK_ADD_YOY', 'LOAN_PBC_ADD_YOY', 'OFI_BF_ADD_YOY', 'RECEIVE_ORIGIC_PREMIUM_YOY', 'RECEIVE_REINSURE_NET_YOY', 'INSURED_INVEST_ADD_YOY', 'DISPOSAL_TFA_ADD_YOY', 'RECEIVE_INTEREST_COMMISSION_YOY', 'BORROW_FUND_ADD_YOY', 'LOAN_ADVANCE_REDUCE_YOY', 'REPO_BUSINESS_ADD_YOY', 'RECEIVE_TAX_REFUND_YOY', 'RECEIVE_OTHER_OPERATE_YOY', 'OPERATE_INFLOW_OTHER_YOY', 'OPERATE_INFLOW_BALANCE_YOY', 'TOTAL_OPERATE_INFLOW_YOY', 'BUY_SERVICES_YOY', 'LOAN_ADVANCE_ADD_YOY', 'PBC_INTERBANK_ADD_YOY', 'PAY_ORIGIC_COMPENSATE_YOY', 'PAY_INTEREST_COMMISSION_YOY', 'PAY_POLICY_BONUS_YOY', 'PAY_STAFF_CASH_YOY', 'PAY_ALL_TAX_YOY', 'PAY_OTHER_OPERATE_YOY', 'OPERATE_OUTFLOW_OTHER_YOY', 'OPERATE_OUTFLOW_BALANCE_YOY', 'TOTAL_OPERATE_OUTFLOW_YOY', 'OPERATE_NETCASH_OTHER_YOY', 'OPERATE_NETCASH_BALANCE_YOY', 'NETCASH_OPERATE_YOY', 'WITHDRAW_INVEST_YOY', 'RECEIVE_INVEST_INCOME_YOY', 'DISPOSAL_LONG_ASSET_YOY', 'DISPOSAL_SUBSIDIARY_OTHER_YOY', 'REDUCE_PLEDGE_TIMEDEPOSITS_YOY', 'RECEIVE_OTHER_INVEST_YOY', 'INVEST_INFLOW_OTHER_YOY', 'INVEST_INFLOW_BALANCE_YOY', 'TOTAL_INVEST_INFLOW_YOY', 'CONSTRUCT_LONG_ASSET_YOY', 'INVEST_PAY_CASH_YOY', 'PLEDGE_LOAN_ADD_YOY', 'OBTAIN_SUBSIDIARY_OTHER_YOY', 'ADD_PLEDGE_TIMEDEPOSITS_YOY', 'PAY_OTHER_INVEST_YOY', 'INVEST_OUTFLOW_OTHER_YOY', 'INVEST_OUTFLOW_BALANCE_YOY', 'TOTAL_INVEST_OUTFLOW_YOY', 'INVEST_NETCASH_OTHER_YOY', 'INVEST_NETCASH_BALANCE_YOY', 'NETCASH_INVEST_YOY', 'ACCEPT_INVEST_CASH_YOY', 'SUBSIDIARY_ACCEPT_INVEST_YOY', 'RECEIVE_LOAN_CASH_YOY', 'ISSUE_BOND_YOY', 'RECEIVE_OTHER_FINANCE_YOY', 'FINANCE_INFLOW_OTHER_YOY', 'FINANCE_INFLOW_BALANCE_YOY', 'TOTAL_FINANCE_INFLOW_YOY', 'PAY_DEBT_CASH_YOY', 'ASSIGN_DIVIDEND_PORFIT_YOY', 'SUBSIDIARY_PAY_DIVIDEND_YOY', 'BUY_SUBSIDIARY_EQUITY_YOY', 'PAY_OTHER_FINANCE_YOY', 'SUBSIDIARY_REDUCE_CASH_YOY', 'FINANCE_OUTFLOW_OTHER_YOY', 'FINANCE_OUTFLOW_BALANCE_YOY', 'TOTAL_FINANCE_OUTFLOW_YOY', 'FINANCE_NETCASH_OTHER_YOY', 'FINANCE_NETCASH_BALANCE_YOY', 'NETCASH_FINANCE_YOY', 'RATE_CHANGE_EFFECT_YOY', 'CCE_ADD_OTHER_YOY', 'CCE_ADD_BALANCE_YOY', 'CCE_ADD_YOY', 'BEGIN_CCE_YOY', 'END_CCE_OTHER_YOY', 'END_CCE_BALANCE_YOY', 'END_CCE_YOY', 'NETPROFIT_YOY', 'ASSET_IMPAIRMENT_YOY', 'FA_IR_DEPR_YOY', 'OILGAS_BIOLOGY_DEPR_YOY', 'IR_DEPR_YOY', 'IA_AMORTIZE_YOY', 'LPE_AMORTIZE_YOY', 'DEFER_INCOME_AMORTIZE_YOY', 'PREPAID_EXPENSE_REDUCE_YOY', 'ACCRUED_EXPENSE_ADD_YOY', 'DISPOSAL_LONGASSET_LOSS_YOY', 'FA_SCRAP_LOSS_YOY', 'FAIRVALUE_CHANGE_LOSS_YOY', 'FINANCE_EXPENSE_YOY', 'INVEST_LOSS_YOY', 'DEFER_TAX_YOY', 'DT_ASSET_REDUCE_YOY', 'DT_LIAB_ADD_YOY', 'PREDICT_LIAB_ADD_YOY', 'INVENTORY_REDUCE_YOY', 'OPERATE_RECE_REDUCE_YOY', 'OPERATE_PAYABLE_ADD_YOY', 'OTHER_YOY', 'OPERATE_NETCASH_OTHERNOTE_YOY', 'OPERATE_NETCASH_BALANCENOTE_YOY', 'NETCASH_OPERATENOTE_YOY', 'DEBT_TRANSFER_CAPITAL_YOY', 'CONVERT_BOND_1YEAR_YOY', 'FINLEASE_OBTAIN_FA_YOY', 'UNINVOLVE_INVESTFIN_OTHER_YOY', 'END_CASH_YOY', 'BEGIN_CASH_YOY', 'END_CASH_EQUIVALENTS_YOY', 'BEGIN_CASH_EQUIVALENTS_YOY', 'CCE_ADD_OTHERNOTE_YOY', 'CCE_ADD_BALANCENOTE_YOY', 'CCE_ADDNOTE_YOY', 'OPINION_TYPE', 'OSOPINION_TYPE', 'MINORITY_INTEREST', 'MINORITY_INTEREST_YOY', 'USERIGHT_ASSET_AMORTIZE', 'USERIGHT_ASSET_AMORTIZE_YOY']

In [35]:
# 现金流量表TRACE项目核心27个有用字段
selected_cashflow_columns = [
    # 经营活动现金流
    "TOTAL_OPERATE_INFLOW",
    "TOTAL_OPERATE_OUTFLOW",
    "NETCASH_OPERATE",
    "SALES_SERVICES",
    "RECEIVE_TAX_REFUND",
    "BUY_SERVICES",
    "PAY_STAFF_CASH",
    "PAY_ALL_TAX",
    # 投资活动现金流
    "NETCASH_INVEST",
    "CONSTRUCT_LONG_ASSET",
    "INVEST_PAY_CASH",
    "WITHDRAW_INVEST",
    "RECEIVE_INVEST_INCOME",
    "DISPOSAL_LONG_ASSET",
    # 筹资活动现金流
    "NETCASH_FINANCE",
    "RECEIVE_LOAN_CASH",
    "PAY_DEBT_CASH",
    "ISSUE_BOND",
    "ACCEPT_INVEST_CASH",
    "ASSIGN_DIVIDEND_PORFIT",
    # 间接法调节附表
    "ASSET_IMPAIRMENT",
    "FA_IR_DEPR",
    "IA_AMORTIZE",
    "INVENTORY_REDUCE",
    "OPERATE_RECE_REDUCE",
    "OPERATE_PAYABLE_ADD",
    # 现金余额校验
    "CCE_ADD",
    "END_CCE"
]

df_cashflow = df_cashflow[selected_cashflow_columns]
df_cashflow

,TOTAL_OPERATE_INFLOW,TOTAL_OPERATE_OUTFLOW,NETCASH_OPERATE,SALES_SERVICES,RECEIVE_TAX_REFUND,BUY_SERVICES,PAY_STAFF_CASH,PAY_ALL_TAX,NETCASH_INVEST,CONSTRUCT_LONG_ASSET,...,ACCEPT_INVEST_CASH,ASSIGN_DIVIDEND_PORFIT,ASSET_IMPAIRMENT,FA_IR_DEPR,IA_AMORTIZE,INVENTORY_REDUCE,OPERATE_RECE_REDUCE,OPERATE_PAYABLE_ADD,CCE_ADD,END_CCE
0,5.618096e+10,2.927107e+10,2.690989e+10,5.639259e+10,NaN,3.211262e+09,7.351815e+09,2.403097e+10,2.563895e+10,6.047916e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.154262e+10,1.779682e+11
1,1.861288e+11,1.246066e+11,6.152220e+10,1.839904e+11,NaN,1.145014e+10,1.547346e+10,7.743060e+10,-3.164190e+10,3.127595e+09,...,NaN,6.724173e+10,NaN,1.893338e+09,2.896137e+08,-7.084137e+09,-1.098388e+10,-6.806428e+09,-4.354448e+10,1.264256e+11
2,1.367335e+11,9.853672e+10,3.819680e+10,1.387917e+11,NaN,8.595278e+09,1.239348e+10,5.910871e+10,-5.423368e+09,2.282862e+09,...,NaN,3.721260e+10,NaN,NaN,NaN,NaN,NaN,NaN,-1.046763e+10,1.595025e+11
3,9.800253e+10,8.488347e+10,1.311906e+10,9.508661e+10,NaN,6.076043e+09,9.965785e+09,4.166989e+10,-3.143510e+08,1.595996e+09,...,NaN,3.467116e+10,NaN,9.407038e+08,1.396685e+08,-6.284468e+08,-2.067915e+10,-1.350559e+10,-2.708483e+10,1.428853e+11
4,5.058425e+10,4.177506e+10,8.809196e+09,5.614406e+10,NaN,2.663148e+09,7.662338e+09,2.216816e+10,-6.242220e+08,9.011043e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.578318e+09,1.765484e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,2.328284e+09,1.893702e+09,4.345824e+08,2.288635e+09,7215268.89,6.235777e+08,1.066845e+08,7.535709e+08,-4.714519e+08,4.674519e+08,...,NaN,1.392593e+08,5977107.72,2.040982e+07,1.700000e+05,-2.902438e+08,-8.106966e+07,3.829405e+08,-1.761289e+08,NaN
94,1.031296e+09,1.211416e+09,-1.801208e+08,1.020057e+09,NaN,3.825321e+08,6.488170e+07,5.828291e+08,-2.647555e+08,2.607555e+08,...,NaN,-2.240036e+06,NaN,9.446489e+06,8.500002e+04,-2.233740e+08,-1.364384e+08,-1.105923e+08,-4.426363e+08,NaN
95,1.846627e+09,1.804344e+09,4.228304e+07,1.800399e+09,1846053.69,5.947081e+08,9.331475e+07,7.021512e+08,-3.316915e+08,3.316915e+08,...,2.016922e+09,1.030607e+08,6692428.52,1.158750e+07,6.760000e+05,-2.747824e+08,-5.751491e+07,2.058185e+07,1.495453e+09,NaN
96,NaN,NaN,-8.628088e+07,NaN,NaN,NaN,NaN,NaN,-1.203369e+06,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.245444e+08,NaN
97,1.330700e+09,8.875758e+08,4.431246e+08,1.322877e+09,4926551.74,2.951323e+08,5.534480e+07,3.716808e+08,-3.382398e+07,3.382398e+07,...,NaN,1.017477e+08,NaN,1.010873e+07,3.477430e+06,-8.893172e+07,2.860930e+08,-9.034529e+07,2.625930e+08,NaN

In [41]:
# --- 4a. 全量 A 股代码+名称（5466行）---
df_list = ak.stock_info_a_code_name()
df_list
# 输出: code / name 两列

        code   name
0     000001   平安银行
1     000002  万  科Ａ
2     000004  *ST国华
3     000006   深振业Ａ
4     000007    全新好
...      ...    ...
5517  920978   开特股份
5518  920981   晶赛科技
5519  920982   锦波生物
5520  920985   海泰新能
5521  920992   中科美菱

[5522 rows x 2 columns]

In [42]:
# --- 4b. 沪市含上市日期、公司全称 ---
df_sh = ak.stock_info_sh_name_code(symbol="主板A股")
df_sh
# 列名: 证券代码 / 证券简称 / 公司全称 / 上市日期

        证券代码  证券简称  证券全称  公司简称                公司全称        上市日期
0     600000  浦发银行  浦发银行  浦发银行      上海浦东发展银行股份有限公司  1999-11-10
1     600004  白云机场  白云机场  白云机场      广州白云国际机场股份有限公司  2003-04-28
2     600006  东风股份  东风股份  东风股份          东风汽车股份有限公司  1999-07-27
3     600007  中国国贸  中国国贸  中国国贸      中国国际贸易中心股份有限公司  1999-03-12
4     600008  首创环保  首创环保  首创环保    北京首创生态环保集团股份有限公司  2000-04-27
...      ...   ...   ...   ...                 ...         ...
1700  605580  恒盛能源  恒盛能源  恒盛能源          恒盛能源股份有限公司  2021-08-19
1701  605588  冠石科技  冠石科技  冠石科技        南京冠石科技股份有限公司  2021-08-12
1702  605589  圣泉集团  圣泉集团  圣泉集团        济南圣泉集团股份有限公司  2021-08-10
1703  605598  上海港湾  上海港湾  上海港湾  上海港湾基础建设(集团)股份有限公司  2021-09-17
1704  605599  菜百股份  菜百股份  菜百股份       北京菜市口百货股份有限公司  2021-09-09

[1705 rows x 6 columns]